version: "3.8"

services:
  # ===================== AUTH =====================
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks: [ innowise-net ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20

  auth-service:
    build:
      context: Authentication-Service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      SERVER_PORT: ${AUTH_PORT}
      DB_URL: jdbc:postgresql://auth-db:5432/${AUTH_POSTGRES_DB}
      DB_USERNAME: ${AUTH_POSTGRES_USER}
      DB_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    networks: [ innowise-net ]


  # ===================== USER =====================
  user-postgres:
    image: postgres:16-alpine
    container_name: user-postgres
    environment:
      POSTGRES_DB: ${USER_POSTGRES_DB}
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
    volumes:
      - user-pgdata:/var/lib/postgresql/data
    networks: [ innowise-net ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20

  user-redis:
    image: redis:7-alpine
    container_name: user-redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - user-redisdata:/data
    networks: [ innowise-net ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20

  user-service:
    build:
      context: ./User-Service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      user-postgres:
        condition: service_healthy
      user-redis:
        condition: service_healthy
    environment:
      SERVER_PORT: ${USER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-postgres:5432/${USER_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${USER_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${USER_POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${USER_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${USER_REDIS_PORT}
    ports:
      - "8081:${USER_PORT}"
    networks: [ innowise-net ]


  # ===================== KAFKA (shared) =====================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks: [ innowise-net ]

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks: [ innowise-net ]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8089:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks: [ innowise-net ]


  # ===================== ORDER =====================
  order-db:
    image: postgres:16-alpine
    container_name: order-db
    environment:
      POSTGRES_DB: ${ORDER_POSTGRES_DB}
      POSTGRES_USER: ${ORDER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ORDER_POSTGRES_PASSWORD}
    volumes:
      - order-pgdata:/var/lib/postgresql/data
    networks: [ innowise-net ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 20

  order-service:
    build:
      context: Order-Service
      dockerfile: Dockerfile
    container_name: order-service
    depends_on:
      order-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SERVER_PORT: ${ORDER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/${ORDER_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${ORDER_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORDER_POSTGRES_PASSWORD}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    ports:
      - "${ORDER_PORT}:${ORDER_PORT}"
    networks: [ innowise-net ]


  # ===================== PAYMENT =====================
  payment-mongo:
    image: mongo:7.0
    container_name: payment-mongo
    restart: unless-stopped
    volumes:
      - payment-mongo-data:/data/db
    networks: [ innowise-net ]
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' localhost:27017/test | grep 1" ]
      interval: 5s
      timeout: 3s
      retries: 30

  payment-service:
    build:
      context: Payment-Service
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    depends_on:
      payment-mongo:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SERVER_PORT: ${PAYMENT_PORT}
      SPRING_DATA_MONGODB_URI: ${PAYMENT_MONGO_URI}
      APP_LIQUIBASE_URL: ${PAYMENT_LIQUIBASE_URL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      EXTERNAL_RANDOM_URL: ${EXTERNAL_RANDOM_URL}
    ports:
      - "${PAYMENT_PORT}:${PAYMENT_PORT}"
    networks: [ innowise-net ]


  # ===================== GATEWAY =====================
  api-gateway:
    build:
      context: ./API-Gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - auth-service
      - user-service
      - order-service
      - payment-service
    environment:
      SERVER_PORT: ${GATEWAY_PORT}
      AUTH_URL: ${AUTH_URL}
      USER_URL: ${USER_SERVICE_URL}
      ORDER_URL: ${ORDER_URL}
      PAYMENT_URL: ${PAYMENT_URL}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks: [ innowise-net ]


volumes:
  auth-db-data:
  user-pgdata:
  user-redisdata:
  order-pgdata:
  payment-mongo-data:

networks:
  innowise-net:
    name: innowise-net
